server:
  port: 8082
spring:
  flyway:
    baseline-on-migrate: true
    table: scheme_version
  application:
    name: easier-boot
  datasource:
    url: jdbc:mysql://${DATABASE_IP:127.0.0.1}:${DATABASE_IP_PORT:3306}/${DATABASE_NAME:easier_boot}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:zt140406?}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
swagger:
  enable: true
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    com:
      kimsoft:
        kims:
          easier:
            boot:
              user:
                mapper: debug


